// ─────────────────────────────────────────────
// DATA: All 38 fishing locations
// ─────────────────────────────────────────────
const LOCATIONS = [
  {
    id: 1,
    name: "Arnarvatn á Melrakkasléttu",
    region: "Norðurland",
    lat: 66.506, lng: -16.124,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. maí – 31. ágúst",
    mStart: 5, mEnd: 8, allYear: false,
    nightFishing: true, fullDay: true, camping: true,
    description: "Arnarvatn er á Melrakkasléttu í norðausturhorni landsins, nálægt Raufarhöfn. Vinsælt svæði fyrir bleikjuveiðar.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Veiði er nokkuð jöfn yfir daginn",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "644 km frá Reykjavík",
    sizeDepth: "3,4 km², dýpst 4 m",
    url: "https://veidikortid.is/veidisvaedi/arnarvatn-a-melrakkaslettu/"
  },
  {
    id: 2,
    name: "Baulárvallarvatn",
    region: "Vesturland",
    lat: 64.912, lng: -22.877,
    hours: "7:00 – 24:00",
    seasonText: "When ice has melted - September 30",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Baulárvallarvatn er á Snæfellsnesi, u.þ.b. 160 km frá Reykjavík. Vatnið er um 1,6 km² og 47 m djúpt á dýpsta stað.",
    fishSpecies: "Urriði",
    fourByFour: false,
    bestTime: "Góð veiði allt sumarið, best í ljósaskiptunum",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "160 km frá Reykjavík",
    sizeDepth: "1,6 km², 47 m djúpt",
    url: "https://veidikortid.is/veidisvaedi/baularvallarvatn/"
  },
  {
    id: 3,
    name: "Berufjarðarvatn",
    region: "Vesturland",
    lat: 65.553, lng: -22.107,
    hours: "7:00 – 23:00",
    seasonText: "15. maí – 15. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: true,
    description: "Berufjarðarvatn er við Berufjörð í Reykhólahreppi á Austur-Barðastrandasýslu. Lítið en fallegt veiðavatn.",
    fishSpecies: "Urriði, bleikja",
    fourByFour: false,
    bestTime: "Fiskur veiðist allt sumarið, morgunn og kvöld best",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "215 km frá Reykjavík",
    sizeDepth: "0,15 km², dýpst 2 m",
    url: "https://veidikortid.is/veidisvaedi/berufjardarvatn/"
  },
  {
    id: 4,
    name: "Elliðavatn",
    region: "Suðurland",
    lat: 64.089, lng: -21.761,
    hours: "7:00 – 24:00",
    seasonText: "Sumardagurinn fyrsti – 15. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Elliðavatn er í Heiðmörk við Reykjavík – vinsælasta veiðivatn höfuðborgarsvæðisins. Bleikja, urriði, lax og sjóbirtingur.",
    fishSpecies: "Bleikja, urriði, lax, sjóbirtingur",
    fourByFour: false,
    bestTime: "Jöfn veiði, sérstaklega vinsælt í maí-júlí. Bestu líkurnar á urriða seint á kvöldin og fyrripart dags",
    legalBaits: "Fluga, ormur og spún (aðeins flugu í Hólmsá)",
    distance: "Í Reykjavík/Kópavogi",
    sizeDepth: "1,8 km², dýpst 2 m",
    url: "https://veidikortid.is/veidisvaedi/ellidavatn/"
  },
  {
    id: 5,
    name: "Frostastaðavatn",
    region: "Suðurland",
    lat: 64.017, lng: -19.047,
    hours: "7:00 – 24:00",
    seasonText: "~ June 20 - September 15",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: true,
    description: "Frostastaðavatn er í Landmannaafrétt á miðhálendinu. Stærsta vatn í vatnaklasanum sunnan Tungnaár. Aðeins aðgengilegt með jeppa.",
    fishSpecies: "Bleikja, urriði, silungur",
    fourByFour: true,
    bestTime: "Veiði best á morgnana og kvöldin",
    legalBaits: "Agn, lifandi eða dautt. Litlar púpur og straumflugur gefa góða veiði",
    distance: "2 klst og 40 mín frá Reykjavík",
    sizeDepth: "2,5 km², dýpst 2 m",
    url: "https://veidikortid.is/veidisvaedi/frostastadavatn/"
  },
  {
    id: 6,
    name: "Gíslholtsvatn",
    region: "Suðurland",
    lat: 63.942, lng: -20.494,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: true,
    description: "Gíslholtsvatn er í Holtahreppi við Rangárþing, um 85 km frá Reykjavík. Tvö vötn eru á svæðinu – Eystra og Vestra Gíslholtsvatn.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Nokkuð jöfn veiði yfir sumarið, urriðinn tekur sérstaklega vel snemma á sumrin",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "85 km frá Reykjavík",
    sizeDepth: "1,6 km², dýpst 8 m",
    url: "https://veidikortid.is/veidisvaedi/gislholtsvatn/"
  },
  {
    id: 7,
    name: "Haugatjarnir",
    region: "Austurland",
    lat: 64.987, lng: -14.615,
    hours: "10:00 – 22:00",
    seasonText: "1. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Haugatjarnir eru tvær litlar tjarnir í Skriðdal, við bæinn Hauga. Hentar vel fyrir fjölskyldur – mikið af fiski þó ekki stór.",
    fishSpecies: "Urriði",
    fourByFour: false,
    bestTime: "Góð veiði allt sumarið",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "650 km frá Reykjavík, 35 km til Egilsstaða",
    sizeDepth: "Tvær litlar tjarnir",
    url: "https://veidikortid.is/veidisvaedi/haugatjarnir/"
  },
  {
    id: 8,
    name: "Haukadalsvatn",
    region: "Vesturland",
    lat: 65.056, lng: -21.647,
    hours: "Morgun til kvölds",
    seasonText: "1. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: true,
    description: "Haukadalsvatn er í Haukadal skammt frá Búðardal, um 140 km frá Reykjavík.",
    fishSpecies: "Sjóbleikja, lax",
    fourByFour: false,
    bestTime: "Besti veiðitíminn frá miðjum júlí og fram í septemberlok",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "140 km frá Reykjavík",
    sizeDepth: "3,2 km², dýpst 40 m",
    url: "https://veidikortid.is/veidisvaedi/haukadalsvatn/"
  },
  {
    id: 9,
    name: "Hítarvatn",
    region: "Vesturland",
    lat: 64.867, lng: -22.001,
    hours: "Morgun til kvölds",
    seasonText: "End of May - August 31",
    mStart: 5, mEnd: 8, allYear: false,
    nightFishing: false, fullDay: false, camping: true,
    description: "Hítarvatn er á Mýrum í Borgarbyggð, um 120 km frá Reykjavík. Stórt vatn, 7,6 km², í 147 m hæð.",
    fishSpecies: "Urriði, bleikja",
    fourByFour: false,
    bestTime: "Nokkuð jöfn veiðivon yfir veiðitímabilið",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "120 km frá Reykjavík",
    sizeDepth: "7,6 km², 147 m hæð",
    url: "https://veidikortid.is/veidisvaedi/hitarvatn/"
  },
  {
    id: 10,
    name: "Hlíðarvatn í Hnappadal",
    region: "Vesturland",
    lat: 64.887, lng: -22.192,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: true,
    description: "Hlíðarvatn er í Kolbeinsstaðahreppi við Heydalsveg nr. 55. Frábært veiðivatn með mikilli veiðivon – hentar sérstaklega vel fyrir fjölskyldur.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Best fyrri hluta sumars, nokkuð jöfn yfir sumarið",
    legalBaits: "Fluga, maðkur, baunir og spónn",
    distance: "130 km frá Reykjavík",
    sizeDepth: "4 km², dýpst 20 m",
    url: "https://veidikortid.is/veidisvaedi/hlidarvatn-i-hnappadal/"
  },
  {
    id: 11,
    name: "Hólmavatn í Dölum",
    region: "Vesturland",
    lat: 65.238, lng: -21.370,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: false,
    description: "Hólmavatn er á Hólmavatnsheiði í Dölum, um 180 km frá Reykjavík. Opið allt árið með sólarhringsveiðar.",
    fishSpecies: "Urriði, bleikja",
    fourByFour: true,
    bestTime: "Góð veiði allt sumarið",
    legalBaits: "Fluga, maðkur og spúnn",
    distance: "180 km frá Reykjavík, 30 km frá Búðardal",
    sizeDepth: "1 km², 190 m hæð",
    url: "https://veidikortid.is/veidisvaedi/holmarvatn/"
  },
  {
    id: 12,
    name: "Hraunhafnarvatn",
    region: "Norðurland",
    lat: 66.521, lng: -16.039,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. maí – 31. ágúst",
    mStart: 5, mEnd: 8, allYear: false,
    nightFishing: true, fullDay: true, camping: true,
    description: "Hraunhafnarvatn er á Melrakkasléttu, við þjóðveg 85 nálægt Raufarhöfn, um 644 km frá Reykjavík.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Veiði er nokkuð jöfn yfir daginn",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "644 km frá Reykjavík",
    sizeDepth: "3,4 km², dýpst 4 m",
    url: "https://veidikortid.is/veidisvaedi/hraunhafnarvatn/"
  },
  {
    id: 13,
    name: "Hraunsfjarðarvatn",
    region: "Vesturland",
    lat: 64.921, lng: -22.912,
    hours: "7:00 – 24:00",
    seasonText: "Þegar ýsa leysir – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Hraunsfjarðarvatn er á Snæfellsnesi, um 160 km frá Reykjavík. Nálægt Baulárvallarvatni.",
    fishSpecies: "Urriði",
    fourByFour: true,
    bestTime: "Góð veiði allt sumarið, best í ljósaskiptunum",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "160 km frá Reykjavík",
    sizeDepth: "2,5 km², 84 m djúpt",
    url: "https://veidikortid.is/veidisvaedi/hraunsfjardarvatn/"
  },
  {
    id: 14,
    name: "Hraunsfjörður",
    region: "Vesturland",
    lat: 64.945, lng: -23.015,
    hours: "7:00 – 23:00",
    seasonText: "1. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: true,
    description: "Hraunsfjörður er á norðanverðu Snæfellsnesi, mitt á milli Stykkishólms og Grundarfjarðar, um 180 km frá Reykjavík.",
    fishSpecies: "Silungur, bleikja, urriði, lax",
    fourByFour: false,
    bestTime: "Mjög góð veiði í júlí og ágúst. Góð vorveiði í apríl-maí",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "180 km frá Reykjavík",
    sizeDepth: "Lón fyrir innan stíflu",
    url: "https://veidikortid.is/veidisvaedi/hraunsfjordur/"
  },
  {
    id: 15,
    name: "Hreðavatn",
    region: "Vesturland",
    lat: 64.761, lng: -21.590,
    hours: "7:00 – 24:00",
    seasonText: "20. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Hreðavatn er í Norðurárdal við þjóðveg 1, um 115 km frá Reykjavík. Aðgengilegt og gjöfult veiðivatn í fallegu umhverfi.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Best fyrri hluta sumars, nokkuð jöfn yfir sumarið",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "115 km frá Reykjavík",
    sizeDepth: "1 km², dýpst 20 m",
    url: "https://veidikortid.is/veidisvaedi/hredavatn/"
  },
  {
    id: 16,
    name: "Kleifarvatn á Reykjanesi",
    region: "Suðurland",
    lat: 63.926, lng: -21.993,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "15. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Kleifarvatn er á Reykjanesskaga, milli Sveifluhálsar og Vatnshlíðar, um 34 km frá Reykjavík. Djúpasta vatn á Reykjanesskaga.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Veiði er nokkuð jöfn yfir daginn",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "34 km frá Reykjavík",
    sizeDepth: "8 km², dýpst 90 m",
    url: "https://veidikortid.is/veidisvaedi/kleifarvatn-a-reykjanesi/"
  },
  {
    id: 17,
    name: "Langavatn",
    region: "Vesturland",
    lat: 64.809, lng: -21.764,
    hours: "7:00 – 24:00",
    seasonText: "15. júní – 20. september",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Langavatn er á Mýrum, í Langadal í Mýrasýslu. Vatnið er aðgengilegt eftir 13 km afleggjarara frá þjóðvegi 1.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Nokkuð jöfn veiði yfir sumarið",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "13 km afleggjari frá þjóðvegi 1",
    sizeDepth: "5,1 km², 36 m dýpi",
    url: "https://veidikortid.is/veidisvaedi/langavatn/"
  },
  {
    id: 18,
    name: "Laxárvatn í Dölum",
    region: "Vesturland",
    lat: 65.213, lng: -21.329,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: false,
    description: "Laxárvatn er á Laxárdalsheiði í Dölum, um 180 km frá Reykjavík. Opið allt árið með sólarhringsveiðar.",
    fishSpecies: "Urriði",
    fourByFour: false,
    bestTime: "Góð veiði allt sumarið",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "180 km frá Reykjavík, 30 km frá Búðardal",
    sizeDepth: "0,5 km², 150 m hæð",
    url: "https://veidikortid.is/veidisvaedi/laxarvatn-i-dolum/"
  },
  {
    id: 19,
    name: "Leirvogsvatn",
    region: "Suðurland",
    lat: 64.199, lng: -21.465,
    hours: "7:00 – 24:00",
    seasonText: "1. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Leirvogsvatn er í Mosfellsbæ, við Þingvallaveginn, um 30 km frá Reykjavík. Um 1,2 km² að flatarmáli.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Nokkuð jöfn veiði yfir sumarið",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "30 km frá Reykjavík",
    sizeDepth: "1,2 km², 16 m dýpi",
    url: "https://veidikortid.is/veidisvaedi/leirvogsvatn/"
  },
  {
    id: 20,
    name: "Ljósavatn",
    region: "Norðurland",
    lat: 65.707, lng: -17.680,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "20. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Ljósavatn er í Ljósavatnsskarði, Suður-Þingeyjarsýslu, um 25 km frá Akureyri.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Jafnan veiðist best á vorin, frá maí og fram í miðjan júlí",
    legalBaits: "Fluga, maðkur og spúnn",
    distance: "25 km frá Akureyri, 425 km frá Reykjavík",
    sizeDepth: "3,2 km², dýpst 35 m",
    url: "https://veidikortid.is/veidisvaedi/ljosavatn/"
  },
  {
    id: 21,
    name: "Meðalfellsvatn",
    region: "Suðurland",
    lat: 64.316, lng: -21.596,
    hours: "7:00 – 22:00",
    seasonText: "19. apríl – 20. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: true,
    description: "Meðalfellsvatn er í Kjósarhreppi, um 50 km frá Reykjavík. Aðgangur um Hvalfjörð og veg nr. 461.",
    fishSpecies: "Bleikja, urriði, sjóbirtingur, lax",
    fourByFour: false,
    bestTime: "Frá miðjum júní og fram í miðjan ágúst. Vorveiðin einnig jafnan góð",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "50 km frá Reykjavík",
    sizeDepth: "2 km², 18 m djúpt",
    url: "https://veidikortid.is/veidisvaedi/medalfellsvatn/"
  },
  {
    id: 22,
    name: "Sauðlauksdalsvatn",
    region: "Vesturland",
    lat: 65.543, lng: -23.986,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "When the ice melts - September 21",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: true,
    description: "Sauðlauksdalsvatn er á Vestfjörðum í nágrenni Patreksfjarðar, um 380 km frá Reykjavík (eða styttri leið með ferju Baldur).",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Kvöldin og morgnarnar hafa reynst best",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "380 km frá Reykjavík, 28 km frá Patreksfirði",
    sizeDepth: "0,35 km², 10 m hæð yfir sjó",
    url: "https://veidikortid.is/veidisvaedi/saudlauksdalsvatn/"
  },
  {
    id: 23,
    name: "Skriðuvatn",
    region: "Austurland",
    lat: 64.960, lng: -14.635,
    hours: "8:00 – 22:00",
    seasonText: "1. júní – 30. september",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: true,
    description: "Skriðuvatn er um 35 km frá Egilsstöðum og 50 km frá Breiðdalsvík. Um 1,25 km² að flatarmáli.",
    fishSpecies: "Urriði, bleikja",
    fourByFour: false,
    bestTime: "Góð veiði allt sumarið",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "35 km frá Egilsstöðum, 595 km frá Reykjavík",
    sizeDepth: "1,25 km², 10 m dýpt",
    url: "https://veidikortid.is/veidisvaedi/skriduvatn/"
  },
  {
    id: 24,
    name: "Sléttuhlíðarvatn",
    region: "Norðurland",
    lat: 66.040, lng: -19.334,
    hours: "8:00 – 24:00",
    seasonText: "1. maí – 20. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: true,
    description: "Sléttuhlíðarvatn er mitt á milli Hofsós og Siglufjarðar, við þjóðveginn í landi Hrauns. Um 360 km frá Reykjavík.",
    fishSpecies: "Sjóbleikja, urriði",
    fourByFour: false,
    bestTime: "Yfirleitt veiðist best í maí og júní, ágætlega allan veiðitímann",
    legalBaits: "Flugu, maðk og spóni",
    distance: "360 km frá Reykjavík, 21 km frá Hofsósi",
    sizeDepth: "0,76 km², 14 m hæð",
    url: "https://veidikortid.is/veidisvaedi/slettuhlidarvatn/"
  },
  {
    id: 25,
    name: "Svínavatn í Húnaþingi",
    region: "Norðurland",
    lat: 65.540, lng: -20.177,
    hours: "7:00 – 24:00",
    seasonText: "1. júní – 31. ágúst",
    mStart: 6, mEnd: 8, allYear: false,
    nightFishing: true, fullDay: false, camping: true,
    description: "Svínavatn er í Húnavatnshreppi, um 240 km frá Reykjavík og 9 km frá þjóðvegi 1.",
    fishSpecies: "Urriði, bleikja",
    fourByFour: false,
    bestTime: "Veiði er nokkuð jöfn yfir daginn og allan veiðitímann",
    legalBaits: "Fluga, maðkur og spúnn",
    distance: "240 km frá Reykjavík",
    sizeDepth: "12 km², dýpst 30 m",
    url: "https://veidikortid.is/veidisvaedi/svinavatn-i-hunathingi/"
  },
  {
    id: 26,
    name: "Syðridalsvatn",
    region: "Vesturland",
    lat: 66.130, lng: -23.248,
    hours: "7:00 – 22:00",
    seasonText: "1. júní – 20. september",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: true,
    description: "Syðridalsvatn er í Bolungarvík við Ísafjarðardjúp á Vestfjörðum, um 470 km frá Reykjavík.",
    fishSpecies: "Bleikja, sjóbleikja, sjóbirtingur, lax",
    fourByFour: false,
    bestTime: "Júlí og ágúst",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "470 km frá Reykjavík",
    sizeDepth: "1 km², 3 m fyrir ofan sjávarmáli",
    url: "https://veidikortid.is/veidisvaedi/sydridalsvatn/"
  },
  {
    id: 27,
    name: "Sænautavatn",
    region: "Austurland",
    lat: 65.264, lng: -15.516,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: true,
    description: "Sænautavatn er á Jökuldalsheiði við Sænautasel, um 600 km frá Reykjavík. Djúpr skurður í miðju vatninu, dýpst 24 m.",
    fishSpecies: "Bleikja",
    fourByFour: false,
    bestTime: "Jöfn veiði yfir veiðitímann, þó yfirleitt meiri í maí og júní",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "600 km frá Reykjavík, 74 km frá Egilsstöðum",
    sizeDepth: "Dýpr skurður 24 m",
    url: "https://veidikortid.is/veidisvaedi/saenautavatn/"
  },
  {
    id: 28,
    name: "Urriðavatn",
    region: "Austurland",
    lat: 65.310, lng: -14.443,
    hours: "Morgun til kvölds",
    seasonText: "Fishing is allowed all year round",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: false, fullDay: false, camping: true,
    description: "Urriðavatn er við Egilsstaði, um 5 km frá bænum. Þjóðvegir 1 og 925 liggja við vatnið. Opið allt árið.",
    fishSpecies: "Bleikja",
    fourByFour: false,
    bestTime: "Fyrst á vorin þegar ísa leysir. Mest veiðist í stillu",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "664 km frá Reykjavík, 5 km frá Egilsstöðum",
    sizeDepth: "1,1 km², dýpst 15 m",
    url: "https://veidikortid.is/veidisvaedi/urridavatn/"
  },
  {
    id: 29,
    name: "Úlfljótsvatn",
    region: "Suðurland",
    lat: 64.100, lng: -21.050,
    hours: "7:00 – 23:00",
    seasonText: "1. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: true,
    description: "Úlfljótsvatn er í Grafningi, sunnan Þingvallavatns. Veiðisvæðið er vestari hluti vatnsins.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Frá miðjum júní og fram í miðjan ágúst",
    legalBaits: "Fluga, spún og maðk",
    distance: "65 km frá Reykjavík (40 km um Nesjavallaleið)",
    sizeDepth: "4 km², yfir 20 m djúpt",
    url: "https://veidikortid.is/veidisvaedi/ulfljotsvatn/"
  },
  {
    id: 30,
    name: "Vatnsdalsvatn",
    region: "Vesturland",
    lat: 65.594, lng: -23.125,
    hours: "7:00 – 23:00",
    seasonText: "1. júní – 20. september",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Vatnsdalsvatn er í Vatnsfirði á Barðaströnd, um 340 km frá Reykjavík. Hægt að stytta leiðina með ferju Baldur.",
    fishSpecies: "Bleikja, sjóbleikja, lax",
    fourByFour: false,
    bestTime: "Frá seinniparts júní og fram í miðjan ágúst",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "340 km frá Reykjavík, 55 km vestur á Patreksfjörð",
    sizeDepth: "2,2 km², dýpst 30 m",
    url: "https://veidikortid.is/veidisvaedi/vatnsdalsvatn/"
  },
  {
    id: 31,
    name: "Vestmannsvatn",
    region: "Norðurland",
    lat: 65.794, lng: -17.432,
    hours: "Morgun til kvölds",
    seasonText: "1. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: true,
    description: "Vestmannsvatn er á mörkum Reykjadals og Aðaldals, um 26 km suður af Húsavík og 455 km frá Reykjavík.",
    fishSpecies: "Bleikja, urriði, lax",
    fourByFour: false,
    bestTime: "Yfirleitt gefur best árla eða seinnipart dags. Jöfn og góð veiði þó yfir daginn",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "455 km frá Reykjavík, 26 km suður af Húsavík",
    sizeDepth: "2,4 km², dýpst 10 m",
    url: "https://veidikortid.is/veidisvaedi/vestmannsvatn/"
  },
  {
    id: 32,
    name: "Vífilsstaðavatn",
    region: "Suðurland",
    lat: 64.077, lng: -21.873,
    hours: "8:00 – 24:00",
    seasonText: "1. apríl – 15. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Vífilsstaðavatn er í Garðabæ, austan við Vífilsstaði. Mjög vinsælt á vorin. Um 0,27 km² að flatarmáli.",
    fishSpecies: "Urriði, vatnableikja",
    fourByFour: false,
    bestTime: "Jafnan veiðist best á vorin, í maí og júní",
    legalBaits: "Aðeins má nota flugu, maðk eða spún",
    distance: "Við Vífilsstaði í Garðabæ",
    sizeDepth: "0,27 km², 38 m hæð yfir sjávarmáli",
    url: "https://veidikortid.is/veidisvaedi/vifilsstadavatn/"
  },
  {
    id: 33,
    name: "Þingvallavatn",
    region: "Suðurland",
    lat: 64.245, lng: -21.090,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Fluguveiðar 20. apr – 1. jún · Alm. veiðar 1. jún – 15. sep",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: true,
    flyOnly: true,
    description: "Þingvallavatn er eitt vinsælasta veiðavatn Íslands – 84 km², 114 m djúpt. 4 tegundir bleikju og víðfrægur urriðastofn. Tjaldstæði við Vatnskot.",
    fishSpecies: "Urriði, kuðungableikja, sílableikja, murta, gjámurta",
    fourByFour: false,
    bestTime: "Fluguveiðar: apríl-maí. Almennar veiðar: júní-september",
    legalBaits: "Aðeins fluga leyfileg",
    distance: "84 km frá Reykjavík",
    sizeDepth: "84 km², 114 m djúpt",
    url: "https://veidikortid.is/veidisvaedi/thingvallavatn/"
  },
  {
    id: 34,
    name: "Þveit",
    region: "Austurland",
    lat: 64.344, lng: -15.256,
    hours: "10:00 – 22:00",
    seasonText: "1. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Þveit er í Nesjahreppi í Austur-Skaftafellssýslu, um 10 km frá Höfn í Hornafirði. Við þjóðveg 1 – auðveldur aðgangur.",
    fishSpecies: "Urriði, bleikja",
    fourByFour: false,
    bestTime: "Góð veiði allt sumarið",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "10 km frá Höfn í Hornafirði, 435 km frá Reykjavík",
    sizeDepth: "0,3 km², dýpst 3 m",
    url: "https://veidikortid.is/veidisvaedi/thveit/"
  },
  {
    id: 35,
    name: "Ölvesvatn – Skagaheiði",
    region: "Norðurland",
    lat: 65.968, lng: -20.049,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Second half of May - mid September",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Ölvesvatn (vatnasvæði Selár) er á Skagaheiði í Skagafirði. Veiðitíminn er veðurháður – yfirleitt opið frá seinni hluta maí.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Veiðitíminn er veðurháður – yfirleitt opið frá seinni hluta maí",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "240 km frá Reykjavík",
    sizeDepth: "0,6 km², 320 m hæð",
    url: "https://veidikortid.is/veidisvaedi/olvesvatn-skagaheidi/"
  },
  {
    id: 36,
    name: "Æðarvatn",
    region: "Norðurland",
    lat: 66.519, lng: -16.102,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. maí – 31. ágúst",
    mStart: 5, mEnd: 8, allYear: false,
    nightFishing: true, fullDay: true, camping: true,
    description: "Æðarvatn er á Melrakkasléttu nálægt Raufarhöfn, um 644 km frá Reykjavík. Við þjóðveg 85.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Veiði er nokkuð jöfn yfir daginn",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "644 km frá Reykjavík",
    sizeDepth: "3,4 km², dýpst 4 m",
    url: "https://veidikortid.is/veidisvaedi/aedarvatn/"
  },
  {
    id: 37,
    name: "Ófærur og Blautulón",
    region: "Suðurland",
    lat: 64.024, lng: -18.527,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: true,
    description: "Ófærur og Blautulón eru á miðhálendinu, um 220 km frá höfuðborgarsvæðinu. Aðeins aðgengilegt með jeppa eftir Fjallabaksleið (F208).",
    fishSpecies: "Bleikja, urriði",
    fourByFour: true,
    bestTime: "Góð veiði allt sumarið",
    legalBaits: "Fluga, maðkur og spónn",
    distance: "220 km frá höfuðborgarsvæðinu",
    sizeDepth: "Ófærur: 0,5 km², Blautulón: 0,3 km²",
    url: "https://veidikortid.is/ofaerur/"
  },
  {
    id: 38,
    name: "Hagavík við Þingvallavatn",
    region: "Suðurland",
    lat: 64.126, lng: -21.163,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. apríl – 15. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    flyOnly: true,
    description: "Hagavík er í Þingvallasveit, um 40 km frá Reykjavík. Aðeins fluguveiðar heimilt. Vinsamlegast skrá afla í veiðibók.",
    fishSpecies: "Bleikja, urriði",
    fourByFour: false,
    bestTime: "Apríl til september",
    legalBaits: "Aðeins fluga leyfileg",
    distance: "40 km frá Reykjavík",
    sizeDepth: "0,3 km²",
    url: "https://veidikortid.is/hagavik/"
  }
];
