// ─────────────────────────────────────────────
// DATA: All 38 fishing locations
// ─────────────────────────────────────────────
const LOCATIONS = [
  {
    id: 1,
    name: "Arnarvatn á Melrakkasléttu",
    region: "Norðurland",
    lat: 66.506, lng: -16.124,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. maí – 31. ágúst",
    mStart: 5, mEnd: 8, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Arnarvatn er á Melrakkasléttu í norðausturhorni landsins, nálægt Raufarhöfn. Vinsælt svæði fyrir bleikjuveiðar.",
    url: "https://veidikortid.is/veidisvaedi/arnarvatn-a-melrakkaslettu/"
  },
  {
    id: 2,
    name: "Baulárvallarvatn",
    region: "Vesturland",
    lat: 64.912, lng: -22.877,
    hours: "7:00 – 24:00",
    seasonText: "Þegar ýsa leysir – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Baulárvallarvatn er á Snæfellsnesi, u.þ.b. 160 km frá Reykjavík. Vatnið er um 1,6 km² og 47 m djúpt á dýpsta stað.",
    url: "https://veidikortid.is/veidisvaedi/baularvallarvatn/"
  },
  {
    id: 3,
    name: "Berufjarðarvatn",
    region: "Vesturland",
    lat: 65.553, lng: -22.107,
    hours: "7:00 – 23:00",
    seasonText: "15. maí – 15. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Berufjarðarvatn er við Berufjörð í Reykhólahreppi á Austur-Barðastrandasýslu. Lítið en fallegt veiðavatn.",
    url: "https://veidikortid.is/veidisvaedi/berufjardarvatn/"
  },
  {
    id: 4,
    name: "Elliðavatn",
    region: "Suðurland",
    lat: 64.089, lng: -21.761,
    hours: "7:00 – 24:00",
    seasonText: "Sumardagurinn fyrsti – 15. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Elliðavatn er í Heiðmörk við Reykjavík – vinsælasta veiðivatn höfuðborgarsvæðisins. Bleikja, urriði, lax og sjóbirtingur.",
    fishSpecies: "Bleikja, urriði, lax, sjóbirtingur",
    url: "https://veidikortid.is/veidisvaedi/ellidavatn/"
  },
  {
    id: 5,
    name: "Frostastaðavatn",
    region: "Suðurland",
    lat: 64.017, lng: -19.047,
    hours: "7:00 – 24:00",
    seasonText: "~20. júní – 15. september (vegfarandi)",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Frostastaðavatn er í Landmannaafrétt á miðhálendinu. Stærsta vatn í vatnaklasanum sunnan Tungnaár. Aðeins aðgengilegt með jeppa.",
    url: "https://veidikortid.is/veidisvaedi/frostastadavatn/"
  },
  {
    id: 6,
    name: "Gíslholtsvatn",
    region: "Suðurland",
    lat: 63.942, lng: -20.494,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: false,
    description: "Gíslholtsvatn er í Holtahreppi við Rangárþing, um 85 km frá Reykjavík. Tvö vötn eru á svæðinu – Eystra og Vestra Gíslholtsvatn.",
    url: "https://veidikortid.is/veidisvaedi/gislholtsvatn/"
  },
  {
    id: 7,
    name: "Haugatjarnir",
    region: "Austurland",
    lat: 64.987, lng: -14.614,
    hours: "10:00 – 22:00",
    seasonText: "1. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Haugatjarnir eru tvær litlar tjarnir í Skriðdal, við bæinn Hauga. Hentar vel fyrir fjölskyldur – mikið af fiski þó ekki stór.",
    url: "https://veidikortid.is/veidisvaedi/haugatjarnir/"
  },
  {
    id: 8,
    name: "Haukadalsvatn",
    region: "Vesturland",
    lat: 65.056, lng: -21.647,
    hours: "Morgun til kvölds",
    seasonText: "1. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Haukadalsvatn er í Haukadal skammt frá Búðardal, um 140 km frá Reykjavík.",
    url: "https://veidikortid.is/veidisvaedi/haukadalsvatn/"
  },
  {
    id: 9,
    name: "Hítarvatn",
    region: "Vesturland",
    lat: 64.867, lng: -22.001,
    hours: "Morgun til kvölds",
    seasonText: "Síðari hluti maí – 31. ágúst",
    mStart: 5, mEnd: 8, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Hítarvatn er á Mýrum í Borgarbyggð, um 120 km frá Reykjavík. Stórt vatn, 7,6 km², í 147 m hæð.",
    url: "https://veidikortid.is/veidisvaedi/hitarvatn/"
  },
  {
    id: 10,
    name: "Hlíðarvatn í Hnappadal",
    region: "Vesturland",
    lat: 64.887, lng: -22.192,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: false,
    description: "Hlíðarvatn er í Kolbeinsstaðahreppi við Heydalsveg nr. 55. Frábært veiðivatn með mikilli veiðivon – hentar sérstaklega vel fyrir fjölskyldur.",
    url: "https://veidikortid.is/veidisvaedi/hlidarvatn-i-hnappadal/"
  },
  {
    id: 11,
    name: "Hólmavatn í Dölum",
    region: "Vesturland",
    lat: 65.238, lng: -21.370,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: false,
    description: "Hólmavatn er á Hólmavatnsheiði í Dölum, um 180 km frá Reykjavík. Opið allt árið með sólarhringsveiðar.",
    url: "https://veidikortid.is/veidisvaedi/holmarvatn/"
  },
  {
    id: 12,
    name: "Hraunhafnarvatn",
    region: "Norðurland",
    lat: 66.521, lng: -16.039,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. maí – 31. ágúst",
    mStart: 5, mEnd: 8, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Hraunhafnarvatn er á Melrakkasléttu, við þjóðveg 85 nálægt Raufarhöfn, um 644 km frá Reykjavík.",
    url: "https://veidikortid.is/veidisvaedi/hraunhafnarvatn/"
  },
  {
    id: 13,
    name: "Hraunsfjarðarvatn",
    region: "Vesturland",
    lat: 64.921, lng: -22.912,
    hours: "7:00 – 24:00",
    seasonText: "Þegar ýsa leysir – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Hraunsfjarðarvatn er á Snæfellsnesi, um 160 km frá Reykjavík. Nálægt Baulárvallarvatni.",
    url: "https://veidikortid.is/veidisvaedi/hraunsfjardarvatn/"
  },
  {
    id: 14,
    name: "Hraunsfjörður",
    region: "Vesturland",
    lat: 64.945, lng: -23.015,
    hours: "7:00 – 23:00",
    seasonText: "1. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Hraunsfjörður er á norðanverðu Snæfellsnesi, mitt á milli Stykkishólms og Grundarfjarðar, um 180 km frá Reykjavík.",
    url: "https://veidikortid.is/veidisvaedi/hraunsfjordur/"
  },
  {
    id: 15,
    name: "Hreðavatn",
    region: "Vesturland",
    lat: 64.761, lng: -21.590,
    hours: "7:00 – 24:00",
    seasonText: "20. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Hreðavatn er í Norðurárdal við þjóðveg 1, um 115 km frá Reykjavík. Aðgengilegt og gjöfult veiðivatn í fallegu umhverfi.",
    url: "https://veidikortid.is/veidisvaedi/hredavatn/"
  },
  {
    id: 16,
    name: "Kleifarvatn á Reykjanesi",
    region: "Suðurland",
    lat: 63.926, lng: -21.993,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "15. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Kleifarvatn er á Reykjanesskaga, milli Sveifluhálsar og Vatnshlíðar, um 34 km frá Reykjavík. Djúpasta vatn á Reykjanesskaga.",
    url: "https://veidikortid.is/veidisvaedi/kleifarvatn-a-reykjanesi/"
  },
  {
    id: 17,
    name: "Langavatn",
    region: "Vesturland",
    lat: 64.809, lng: -21.764,
    hours: "7:00 – 24:00",
    seasonText: "15. júní – 20. september",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Langavatn er á Mýrum, í Langadal í Mýrasýslu. Vatnið er aðgengilegt eftir 13 km afleggjarara frá þjóðvegi 1.",
    url: "https://veidikortid.is/veidisvaedi/langavatn/"
  },
  {
    id: 18,
    name: "Laxárvatn í Dölum",
    region: "Vesturland",
    lat: 65.213, lng: -21.329,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: false,
    description: "Laxárvatn er á Laxárdalsheiði í Dölum, um 180 km frá Reykjavík. Opið allt árið með sólarhringsveiðar.",
    url: "https://veidikortid.is/veidisvaedi/laxarvatn-i-dolum/"
  },
  {
    id: 19,
    name: "Leirvogsvatn",
    region: "Suðurland",
    lat: 64.199, lng: -21.465,
    hours: "7:00 – 24:00",
    seasonText: "1. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Leirvogsvatn er í Mosfellsbæ, við Þingvallaveginn, um 30 km frá Reykjavík. Um 1,2 km² að flatarmáli.",
    url: "https://veidikortid.is/veidisvaedi/leirvogsvatn/"
  },
  {
    id: 20,
    name: "Ljósavatn",
    region: "Norðurland",
    lat: 65.707, lng: -17.680,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "20. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Ljósavatn er í Ljósavatnsskarði, Suður-Þingeyjarsýslu, um 25 km frá Akureyri.",
    url: "https://veidikortid.is/veidisvaedi/ljosavatn/"
  },
  {
    id: 21,
    name: "Meðalfellsvatn",
    region: "Suðurland",
    lat: 64.316, lng: -21.596,
    hours: "7:00 – 22:00",
    seasonText: "19. apríl – 20. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Meðalfellsvatn er í Kjósarhreppi, um 50 km frá Reykjavík. Aðgangur um Hvalfjörð og veg nr. 461.",
    url: "https://veidikortid.is/veidisvaedi/medalfellsvatn/"
  },
  {
    id: 22,
    name: "Sauðlauksdalsvatn",
    region: "Vesturland",
    lat: 65.543, lng: -23.987,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Þegar ýsa leysir – haust",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Sauðlauksdalsvatn er á Vestfjörðum í nágrenni Patreksfjarðar, um 380 km frá Reykjavík (eða styttri leið með ferju Baldur).",
    url: "https://veidikortid.is/veidisvaedi/saudlauksdalsvatn/"
  },
  {
    id: 23,
    name: "Skriðuvatn",
    region: "Austurland",
    lat: 64.960, lng: -14.635,
    hours: "8:00 – 22:00",
    seasonText: "1. júní – 30. september",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Skriðuvatn er um 35 km frá Egilsstöðum og 50 km frá Breiðdalsvík. Um 1,25 km² að flatarmáli.",
    url: "https://veidikortid.is/veidisvaedi/skriduvatn/"
  },
  {
    id: 24,
    name: "Sléttuhlíðarvatn",
    region: "Norðurland",
    lat: 66.040, lng: -19.334,
    hours: "8:00 – 24:00",
    seasonText: "1. maí – 20. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Sléttuhlíðarvatn er mitt á milli Hofsós og Siglufjarðar, við þjóðveginn í landi Hrauns. Um 360 km frá Reykjavík.",
    url: "https://veidikortid.is/veidisvaedi/slettuhlidarvatn/"
  },
  {
    id: 25,
    name: "Svínavatn í Húnaþingi",
    region: "Norðurland",
    lat: 65.540, lng: -20.177,
    hours: "7:00 – 24:00",
    seasonText: "1. júní – 31. ágúst",
    mStart: 6, mEnd: 8, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Svínavatn er í Húnavatnshreppi, um 240 km frá Reykjavík og 9 km frá þjóðvegi 1.",
    url: "https://veidikortid.is/veidisvaedi/svinavatn-i-hunathingi/"
  },
  {
    id: 26,
    name: "Syðridalsvatn",
    region: "Vesturland",
    lat: 66.130, lng: -23.248,
    hours: "7:00 – 22:00",
    seasonText: "1. júní – 20. september",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Syðridalsvatn er í Bolungarvík við Ísafjarðardjúp á Vestfjörðum, um 470 km frá Reykjavík.",
    url: "https://veidikortid.is/veidisvaedi/sydridalsvatn/"
  },
  {
    id: 27,
    name: "Sænautavatn",
    region: "Austurland",
    lat: 65.264, lng: -15.517,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Sænautavatn er á Jökuldalsheiði við Sænautasel, um 600 km frá Reykjavík. Djúpr skurður í miðju vatninu, dýpst 24 m.",
    url: "https://veidikortid.is/veidisvaedi/saenautavatn/"
  },
  {
    id: 28,
    name: "Urriðavatn",
    region: "Austurland",
    lat: 65.309, lng: -14.436,
    hours: "Morgun til kvölds",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: false, fullDay: false, camping: false,
    description: "Urriðavatn er við Egilsstaði, um 5 km frá bænum. Þjóðvegir 1 og 925 liggja við vatnið. Opið allt árið.",
    url: "https://veidikortid.is/veidisvaedi/urridavatn/"
  },
  {
    id: 29,
    name: "Úlfljótsvatn",
    region: "Suðurland",
    lat: 64.100, lng: -21.050,
    hours: "7:00 – 23:00",
    seasonText: "1. maí – 30. september",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Úlfljótsvatn er í Grafningi, sunnan Þingvallavatns. Veiðisvæðið er vestari hluti vatnsins.",
    url: "https://veidikortid.is/veidisvaedi/ulfljotsvatn/"
  },
  {
    id: 30,
    name: "Vatnsdalsvatn",
    region: "Vesturland",
    lat: 65.594, lng: -23.125,
    hours: "7:00 – 23:00",
    seasonText: "1. júní – 20. september",
    mStart: 6, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Vatnsdalsvatn er í Vatnsfirði á Barðaströnd, um 340 km frá Reykjavík. Hægt að stytta leiðina með ferju Baldur.",
    url: "https://veidikortid.is/veidisvaedi/vatnsdalsvatn/"
  },
  {
    id: 31,
    name: "Vestmannsvatn",
    region: "Norðurland",
    lat: 65.794, lng: -17.432,
    hours: "Morgun til kvölds",
    seasonText: "1. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Vestmannsvatn er á mörkum Reykjadals og Aðaldals, um 26 km suður af Húsavík og 455 km frá Reykjavík.",
    url: "https://veidikortid.is/veidisvaedi/vestmannsvatn/"
  },
  {
    id: 32,
    name: "Vífilsstaðavatn",
    region: "Suðurland",
    lat: 64.147, lng: -21.85,
    hours: "8:00 – 24:00",
    seasonText: "1. apríl – 15. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: false, camping: false,
    description: "Vífilsstaðavatn er í Garðabæ, austan við Vífilsstaði. Mjög vinsælt á vorin. Um 0,27 km² að flatarmáli.",
    url: "https://veidikortid.is/veidisvaedi/vifilsstadavatn/"
  },
  {
    id: 33,
    name: "Þingvallavatn",
    region: "Suðurland",
    lat: 64.225, lng: -21.10,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Fluguveiðar 20. apr – 1. jún · Alm. veiðar 1. jún – 15. sep",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: true,
    flyOnly: true,
    description: "Þingvallavatn er eitt vinsælasta veiðavatn Íslands – 84 km², 114 m djúpt. 4 tegundir bleikju og víðfrægur urriðastofn. Tjaldstæði við Vatnskot.",
    fishSpecies: "Urriði, kuðungableikja, sílableikja, murta, gjámurta",
    url: "https://veidikortid.is/veidisvaedi/thingvallavatn/"
  },
  {
    id: 34,
    name: "Þveit",
    region: "Austurland",
    lat: 64.344, lng: -15.256,
    hours: "10:00 – 22:00",
    seasonText: "1. apríl – 30. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: false, fullDay: false, camping: false,
    description: "Þveit er í Nesjahreppi í Austur-Skaftafellssýslu, um 10 km frá Höfn í Hornafirði. Við þjóðveg 1 – auðveldur aðgangur.",
    url: "https://veidikortid.is/veidisvaedi/thveit/"
  },
  {
    id: 35,
    name: "Ölvesvatn – Skagaheiði",
    region: "Norðurland",
    lat: 65.968, lng: -20.049,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Seinni hluti maí – miðjan september (veðurháð)",
    mStart: 5, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Ölvesvatn (vatnasvæði Selár) er á Skagaheiði í Skagafirði. Veiðitíminn er veðurháður – yfirleitt opið frá seinni hluta maí.",
    url: "https://veidikortid.is/veidisvaedi/olvesvatn-skagaheidi/"
  },
  {
    id: 36,
    name: "Æðarvatn",
    region: "Norðurland",
    lat: 66.519, lng: -16.102,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. maí – 31. ágúst",
    mStart: 5, mEnd: 8, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    description: "Æðarvatn er á Melrakkasléttu nálægt Raufarhöfn, um 644 km frá Reykjavík. Við þjóðveg 85.",
    url: "https://veidikortid.is/veidisvaedi/aedarvatn/"
  },
  {
    id: 37,
    name: "Ófærur og Blautulón",
    region: "Suðurland",
    lat: 64.023, lng: -18.538,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "Opið allt árið",
    mStart: 1, mEnd: 12, allYear: true,
    nightFishing: true, fullDay: true, camping: false,
    description: "Ófærur og Blautulón eru á miðhálendinu, um 220 km frá höfuðborgarsvæðinu. Aðeins aðgengilegt með jeppa eftir Fjallabaksleið (F208).",
    url: "https://veidikortid.is/ofaerur/"
  },
  {
    id: 38,
    name: "Hagavík við Þingvallavatn",
    region: "Suðurland",
    lat: 64.124, lng: -21.165,
    hours: "Sólarhringsveiði (24h)",
    seasonText: "1. apríl – 15. september",
    mStart: 4, mEnd: 9, allYear: false,
    nightFishing: true, fullDay: true, camping: false,
    flyOnly: true,
    description: "Hagavík er í Þingvallasveit, um 40 km frá Reykjavík. Aðeins fluguveiðar heimilt. Vinsamlegast skrá afla í veiðibók.",
    url: "https://veidikortid.is/hagavik/"
  }
];
